apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xmijn99sw-dotnet-basic
  janus-idp.io/tekton: xmijn99sw-dotnet-basic
  backstage.io/kubernetes-id: xmijn99sw-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xmijn99sw-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
