apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xmijn99sw-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/xmijn99sw-dotnet-basic